// <auto-generated />
namespace TradeProAssistant.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddPairEligible : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPairEligible));
        
        string IMigrationMetadata.Id
        {
            get { return "202001082249331_AddPairEligible"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
