// <auto-generated />
namespace TradeProAssistant.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddSectorEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSectorEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "202001082220261_AddSectorEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
